name: task_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  pinput: ^2.2.12
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  flutter_native_image: ^0.0.6
  syncfusion_flutter_pdfviewer: ^20.3.52
  flutter_native_splash: ^2.2.4
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.0
  device_preview: ^1.1.0
  bloc: ^8.0.3
  dio: ^4.0.6
  json_serializable: ^6.1.4
  retrofit: ^3.0.1+1
  analyzer: ^4.2.0
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+3
  get_it: ^7.2.0
  injectable: ^1.5.3
  lottie: ^1.2.2
  freezed: ^2.0.3+1
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  cached_network_image: ^3.2.1
  permission_handler: ^10.0.0
  infinite_scroll_pagination: ^3.2.0
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  file_picker: ^5.0.1
  flash: ^2.0.3+3
  flutter_styled_toast: ^2.0.0
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_polyline_points: ^1.0.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
dev_dependencies:
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.1
  injectable_generator: ^1.5.3
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter 

flutter:
  #generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/
    
  fonts:
    - family: bank
      fonts:
        - asset: assets/fonts/ar/bank_Bold.ttf
          weight: 700
        - asset: assets/fonts/ar/bank_Regular.ttf
          weight: 400


flutter_native_splash:
  color: "#D8044F"
  image: assets/images/app_logo_splash.png
  android: true
  ios: true

  # flutter packages pub run build_runner watch --delete-conflicting-outputs